In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import scipy.stats as stat

In [3]:
path="/Users/nemanja/Downloads/asian_countries.csv"
dfwh=pd.read_csv(path,skiprows=1,header=None)
print(dfwh)

              0     1           2     3    4   5     6          7     8   \
0    Afghanistan  2015  Developing  65.0  263  62  0.01  71.279624  65.0
1    Afghanistan  2014  Developing  59.9  271  64  0.01  73.523582  62.0
2    Afghanistan  2013  Developing  59.9  268  66  0.01  73.219243  64.0
3    Afghanistan  2012  Developing  59.5  272  69  0.01  78.184215  67.0
4    Afghanistan  2011  Developing  59.2  275  71  0.01   7.097109  68.0
..           ...   ...         ...   ...  ...  ..   ...        ...   ...
271        Yemen  2014  Developing  65.4  228  37  0.01   0.000000  73.0
272        Yemen  2013  Developing  65.4  226  36  0.04   0.000000  73.0
273        Yemen  2012  Developing  64.7  236  36  0.04   0.000000  67.0
274        Yemen  2011  Developing  64.6  234  35  0.04   0.000000  69.0
275        Yemen  2010  Developing  64.4  233  35  0.06   0.000000  76.0

       9   ...  12    13  14   15          16          17    18    19     20  \
0    1154  ...   6  8.16  65  0.1  584.259210  33736494.0  17.2  17.3  0.479
1     492  ...  58  8.18  62  0.1  612.696514    327582.0  17.5  17.5  0.476
2     430  ...  62  8.13  64  0.1  631.744976  31731688.0  17.7  17.7  0.470
3    2787  ...  67  8.52  67  0.1  669.959000   3696958.0  17.9  18.0  0.463
4    3013  ...  68  7.87  68  0.1   63.537231   2978599.0  18.2  18.2  0.454
..    ...  ...  ..   ...  ..  ...         ...         ...   ...   ...    ...
271   815  ...  67  5.64  73  0.1         NaN         NaN  13.7  13.5  0.500
272   400  ...  67  5.78  73  0.1         NaN         NaN  13.7  13.5  0.498
273  2177  ...  68  5.73  67  0.1         NaN         NaN  13.7  13.6  0.494
274  2676  ...  69  5.40  69  0.1         NaN         NaN  13.7  13.6  0.493
275   510  ...  77  5.17  76  0.1         NaN         NaN  13.7  13.7  0.488

       21
0    10.1
1    10.0
2     9.9
3     9.8
4     9.5
..    ...
271   9.0
272   9.0
273   9.0
274   8.6
275   8.5

[276 rows x 22 columns]

In [4]:
print(dfwh.dtypes)

0      object
1       int64
2      object
3     float64
4       int64
5       int64
6     float64
7     float64
8     float64
9       int64
10    float64
11      int64
12      int64
13    float64
14      int64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
dtype: object

In [5]:
df=pd.read_csv(path)
print(df)

         Country  Year      Status  Life expectancy   Adult Mortality  \
0    Afghanistan  2015  Developing              65.0              263
1    Afghanistan  2014  Developing              59.9              271
2    Afghanistan  2013  Developing              59.9              268
3    Afghanistan  2012  Developing              59.5              272
4    Afghanistan  2011  Developing              59.2              275
..           ...   ...         ...               ...              ...
271        Yemen  2014  Developing              65.4              228
272        Yemen  2013  Developing              65.4              226
273        Yemen  2012  Developing              64.7              236
274        Yemen  2011  Developing              64.6              234
275        Yemen  2010  Developing              64.4              233

     infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0               62     0.01               71.279624         65.0      1154
1               64     0.01               73.523582         62.0       492
2               66     0.01               73.219243         64.0       430
3               69     0.01               78.184215         67.0      2787
4               71     0.01                7.097109         68.0      3013
..             ...      ...                     ...          ...       ...
271             37     0.01                0.000000         73.0       815
272             36     0.04                0.000000         73.0       400
273             36     0.04                0.000000         67.0      2177
274             35     0.04                0.000000         69.0      2676
275             35     0.06                0.000000         76.0       510

     ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0    ...      6               8.16           65        0.1  584.259210
1    ...     58               8.18           62        0.1  612.696514
2    ...     62               8.13           64        0.1  631.744976
3    ...     67               8.52           67        0.1  669.959000
4    ...     68               7.87           68        0.1   63.537231
..   ...    ...                ...          ...        ...         ...
271  ...     67               5.64           73        0.1         NaN
272  ...     67               5.78           73        0.1         NaN
273  ...     68               5.73           67        0.1         NaN
274  ...     69               5.40           69        0.1         NaN
275  ...     77               5.17           76        0.1         NaN

     Population   thinness  1-19 years   thinness 5-9 years  \
0    33736494.0                   17.2                 17.3
1      327582.0                   17.5                 17.5
2    31731688.0                   17.7                 17.7
3     3696958.0                   17.9                 18.0
4     2978599.0                   18.2                 18.2
..          ...                    ...                  ...
271         NaN                   13.7                 13.5
272         NaN                   13.7                 13.5
273         NaN                   13.7                 13.6
274         NaN                   13.7                 13.6
275         NaN                   13.7                 13.7

     Income composition of resources  Schooling
0                              0.479       10.1
1                              0.476       10.0
2                              0.470        9.9
3                              0.463        9.8
4                              0.454        9.5
..                               ...        ...
271                            0.500        9.0
272                            0.498        9.0
273                            0.494        9.0
274                            0.493        8.6
275                            0.488        8.5

[276 rows x 22 columns]

In [6]:
print(dfwh.describe())
print(dfwh.describe(include="all"))

                1           3           4            5           6   \
count   276.000000  276.000000  276.000000   276.000000  232.000000
mean   2012.500000   72.360507  125.057971    49.713768    2.074871
std       1.710927    5.271943   72.258200   161.868952    2.743139
min    2010.000000   58.800000    6.000000     0.000000    0.010000
25%    2011.000000   68.250000   68.750000     1.000000    0.010000
50%    2012.500000   73.900000  127.000000     6.500000    0.770000
75%    2014.000000   75.800000  183.000000    22.000000    2.907500
max    2015.000000   85.000000  294.000000  1200.000000   11.320000

                7           8             9           10           11  \
count   276.000000  270.000000    276.000000  276.000000   276.000000
mean    516.505442   88.737037   2969.862319   37.749638    62.427536
std    1231.002196   16.576547  10127.377331   19.896672   208.526062
min       0.000000    4.000000      0.000000    2.100000     0.000000
25%       0.000000   85.250000      4.000000   19.750000     1.000000
50%      67.687008   96.000000    112.500000   37.650000     7.500000
75%     276.595890   98.000000   1038.250000   56.050000    25.250000
max    9498.729062   99.000000  90387.000000   71.400000  1600.000000

               12          13          14          15            16  \
count  276.000000  231.000000  276.000000  276.000000    240.000000
mean    87.728261    4.815887   89.641304    0.137319   9319.472277
std     20.560918    2.128190   15.050882    0.093140  16037.186787
min      5.000000    0.760000    6.000000    0.100000     14.142268
25%     86.000000    3.240000   86.750000    0.100000    865.994668
50%     96.000000    4.480000   96.000000    0.100000   2975.418670
75%     99.000000    6.400000   98.000000    0.100000   7691.703225
max     99.000000   13.730000   99.000000    0.600000  88564.822980

                 17          18          19          20          21
count  1.980000e+02  276.000000  276.000000  276.000000  276.000000
mean   2.841118e+07    7.248551    7.436957    0.699072   12.554710
std    1.034014e+08    5.973252    5.967312    0.128333    1.881493
min    4.100000e+01    0.900000    1.000000    0.000000    7.500000
25%    1.357058e+05    2.675000    2.900000    0.614500   11.500000
50%    1.674080e+06    5.100000    5.100000    0.721500   12.800000
75%    1.471712e+07   11.000000   11.125000    0.790500   13.800000
max    1.293859e+09   27.000000   27.800000    0.924000   16.100000
                 0            1           2           3           4   \
count           276   276.000000         276  276.000000  276.000000
unique           46          NaN           2         NaN         NaN
top     Afghanistan          NaN  Developing         NaN         NaN
freq              6          NaN         258         NaN         NaN
mean            NaN  2012.500000         NaN   72.360507  125.057971
std             NaN     1.710927         NaN    5.271943   72.258200
min             NaN  2010.000000         NaN   58.800000    6.000000
25%             NaN  2011.000000         NaN   68.250000   68.750000
50%             NaN  2012.500000         NaN   73.900000  127.000000
75%             NaN  2014.000000         NaN   75.800000  183.000000
max             NaN  2015.000000         NaN   85.000000  294.000000

                 5           6            7           8             9   ...  \
count    276.000000  232.000000   276.000000  270.000000    276.000000  ...
unique          NaN         NaN          NaN         NaN           NaN  ...
top             NaN         NaN          NaN         NaN           NaN  ...
freq            NaN         NaN          NaN         NaN           NaN  ...
mean      49.713768    2.074871   516.505442   88.737037   2969.862319  ...
std      161.868952    2.743139  1231.002196   16.576547  10127.377331  ...
min        0.000000    0.010000     0.000000    4.000000      0.000000  ...
25%        1.000000    0.010000     0.000000   85.250000      4.000000  ...
50%        6.500000    0.770000    67.687008   96.000000    112.500000  ...
75%       22.000000    2.907500   276.595890   98.000000   1038.250000  ...
max     1200.000000   11.320000  9498.729062   99.000000  90387.000000  ...

                12          13          14          15            16  \
count   276.000000  231.000000  276.000000  276.000000    240.000000
unique         NaN         NaN         NaN         NaN           NaN
top            NaN         NaN         NaN         NaN           NaN
freq           NaN         NaN         NaN         NaN           NaN
mean     87.728261    4.815887   89.641304    0.137319   9319.472277
std      20.560918    2.128190   15.050882    0.093140  16037.186787
min       5.000000    0.760000    6.000000    0.100000     14.142268
25%      86.000000    3.240000   86.750000    0.100000    865.994668
50%      96.000000    4.480000   96.000000    0.100000   2975.418670
75%      99.000000    6.400000   98.000000    0.100000   7691.703225
max      99.000000   13.730000   99.000000    0.600000  88564.822980

                  17          18          19          20          21
count   1.980000e+02  276.000000  276.000000  276.000000  276.000000
unique           NaN         NaN         NaN         NaN         NaN
top              NaN         NaN         NaN         NaN         NaN
freq             NaN         NaN         NaN         NaN         NaN
mean    2.841118e+07    7.248551    7.436957    0.699072   12.554710
std     1.034014e+08    5.973252    5.967312    0.128333    1.881493
min     4.100000e+01    0.900000    1.000000    0.000000    7.500000
25%     1.357058e+05    2.675000    2.900000    0.614500   11.500000
50%     1.674080e+06    5.100000    5.100000    0.721500   12.800000
75%     1.471712e+07   11.000000   11.125000    0.790500   13.800000
max     1.293859e+09   27.000000   27.800000    0.924000   16.100000

[11 rows x 22 columns]

In [7]:
df.isnull().sum()

Country                             0
Year                                0
Status                              0
Life expectancy                     0
Adult Mortality                     0
infant deaths                       0
Alcohol                            44
percentage expenditure              0
Hepatitis B                         6
Measles                             0
 BMI                                0
under-five deaths                   0
Polio                               0
Total expenditure                  45
Diphtheria                          0
 HIV/AIDS                           0
GDP                                36
Population                         78
 thinness  1-19 years               0
 thinness 5-9 years                 0
Income composition of resources     0
Schooling                           0
dtype: int64

In [9]:
mean_value=df['GDP'].mean()
df['GDP'].fillna(value=mean_value, inplace=True)
print(df)

         Country  Year      Status  Life expectancy   Adult Mortality  \
0    Afghanistan  2015  Developing              65.0              263
1    Afghanistan  2014  Developing              59.9              271
2    Afghanistan  2013  Developing              59.9              268
3    Afghanistan  2012  Developing              59.5              272
4    Afghanistan  2011  Developing              59.2              275
..           ...   ...         ...               ...              ...
271        Yemen  2014  Developing              65.4              228
272        Yemen  2013  Developing              65.4              226
273        Yemen  2012  Developing              64.7              236
274        Yemen  2011  Developing              64.6              234
275        Yemen  2010  Developing              64.4              233

     infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0               62     0.01               71.279624         65.0      1154
1               64     0.01               73.523582         62.0       492
2               66     0.01               73.219243         64.0       430
3               69     0.01               78.184215         67.0      2787
4               71     0.01                7.097109         68.0      3013
..             ...      ...                     ...          ...       ...
271             37     0.01                0.000000         73.0       815
272             36     0.04                0.000000         73.0       400
273             36     0.04                0.000000         67.0      2177
274             35     0.04                0.000000         69.0      2676
275             35     0.06                0.000000         76.0       510

     ...  Polio  Total expenditure  Diphtheria    HIV/AIDS          GDP  \
0    ...      6               8.16           65        0.1   584.259210
1    ...     58               8.18           62        0.1   612.696514
2    ...     62               8.13           64        0.1   631.744976
3    ...     67               8.52           67        0.1   669.959000
4    ...     68               7.87           68        0.1    63.537231
..   ...    ...                ...          ...        ...          ...
271  ...     67               5.64           73        0.1  9319.472277
272  ...     67               5.78           73        0.1  9319.472277
273  ...     68               5.73           67        0.1  9319.472277
274  ...     69               5.40           69        0.1  9319.472277
275  ...     77               5.17           76        0.1  9319.472277

     Population   thinness  1-19 years   thinness 5-9 years  \
0    33736494.0                   17.2                 17.3
1      327582.0                   17.5                 17.5
2    31731688.0                   17.7                 17.7
3     3696958.0                   17.9                 18.0
4     2978599.0                   18.2                 18.2
..          ...                    ...                  ...
271         NaN                   13.7                 13.5
272         NaN                   13.7                 13.5
273         NaN                   13.7                 13.6
274         NaN                   13.7                 13.6
275         NaN                   13.7                 13.7

     Income composition of resources  Schooling
0                              0.479       10.1
1                              0.476       10.0
2                              0.470        9.9
3                              0.463        9.8
4                              0.454        9.5
..                               ...        ...
271                            0.500        9.0
272                            0.498        9.0
273                            0.494        9.0
274                            0.493        8.6
275                            0.488        8.5

[276 rows x 22 columns]

In [10]:
df.isnull().sum()

Country                             0
Year                                0
Status                              0
Life expectancy                     0
Adult Mortality                     0
infant deaths                       0
Alcohol                            44
percentage expenditure              0
Hepatitis B                         6
Measles                             0
 BMI                                0
under-five deaths                   0
Polio                               0
Total expenditure                  45
Diphtheria                          0
 HIV/AIDS                           0
GDP                                 0
Population                         78
 thinness  1-19 years               0
 thinness 5-9 years                 0
Income composition of resources     0
Schooling                           0
dtype: int64

In [11]:
mean_value=df['Population'].mean()
df['Population'].fillna(value=mean_value, inplace=True)
print(df)

         Country  Year      Status  Life expectancy   Adult Mortality  \
0    Afghanistan  2015  Developing              65.0              263
1    Afghanistan  2014  Developing              59.9              271
2    Afghanistan  2013  Developing              59.9              268
3    Afghanistan  2012  Developing              59.5              272
4    Afghanistan  2011  Developing              59.2              275
..           ...   ...         ...               ...              ...
271        Yemen  2014  Developing              65.4              228
272        Yemen  2013  Developing              65.4              226
273        Yemen  2012  Developing              64.7              236
274        Yemen  2011  Developing              64.6              234
275        Yemen  2010  Developing              64.4              233

     infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0               62     0.01               71.279624         65.0      1154
1               64     0.01               73.523582         62.0       492
2               66     0.01               73.219243         64.0       430
3               69     0.01               78.184215         67.0      2787
4               71     0.01                7.097109         68.0      3013
..             ...      ...                     ...          ...       ...
271             37     0.01                0.000000         73.0       815
272             36     0.04                0.000000         73.0       400
273             36     0.04                0.000000         67.0      2177
274             35     0.04                0.000000         69.0      2676
275             35     0.06                0.000000         76.0       510

     ...  Polio  Total expenditure  Diphtheria    HIV/AIDS          GDP  \
0    ...      6               8.16           65        0.1   584.259210
1    ...     58               8.18           62        0.1   612.696514
2    ...     62               8.13           64        0.1   631.744976
3    ...     67               8.52           67        0.1   669.959000
4    ...     68               7.87           68        0.1    63.537231
..   ...    ...                ...          ...        ...          ...
271  ...     67               5.64           73        0.1  9319.472277
272  ...     67               5.78           73        0.1  9319.472277
273  ...     68               5.73           67        0.1  9319.472277
274  ...     69               5.40           69        0.1  9319.472277
275  ...     77               5.17           76        0.1  9319.472277

       Population   thinness  1-19 years   thinness 5-9 years  \
0    3.373649e+07                   17.2                 17.3
1    3.275820e+05                   17.5                 17.5
2    3.173169e+07                   17.7                 17.7
3    3.696958e+06                   17.9                 18.0
4    2.978599e+06                   18.2                 18.2
..            ...                    ...                  ...
271  2.841118e+07                   13.7                 13.5
272  2.841118e+07                   13.7                 13.5
273  2.841118e+07                   13.7                 13.6
274  2.841118e+07                   13.7                 13.6
275  2.841118e+07                   13.7                 13.7

     Income composition of resources  Schooling
0                              0.479       10.1
1                              0.476       10.0
2                              0.470        9.9
3                              0.463        9.8
4                              0.454        9.5
..                               ...        ...
271                            0.500        9.0
272                            0.498        9.0
273                            0.494        9.0
274                            0.493        8.6
275                            0.488        8.5

[276 rows x 22 columns]

In [12]:
df.isnull().sum()

Country                             0
Year                                0
Status                              0
Life expectancy                     0
Adult Mortality                     0
infant deaths                       0
Alcohol                            44
percentage expenditure              0
Hepatitis B                         6
Measles                             0
 BMI                                0
under-five deaths                   0
Polio                               0
Total expenditure                  45
Diphtheria                          0
 HIV/AIDS                           0
GDP                                 0
Population                          0
 thinness  1-19 years               0
 thinness 5-9 years                 0
Income composition of resources     0
Schooling                           0
dtype: int64

In [13]:
df=df.drop(df.columns[[6,7,13,18,19]], axis=1)

In [14]:
print(df)

         Country  Year      Status  Life expectancy   Adult Mortality  \
0    Afghanistan  2015  Developing              65.0              263
1    Afghanistan  2014  Developing              59.9              271
2    Afghanistan  2013  Developing              59.9              268
3    Afghanistan  2012  Developing              59.5              272
4    Afghanistan  2011  Developing              59.2              275
..           ...   ...         ...               ...              ...
271        Yemen  2014  Developing              65.4              228
272        Yemen  2013  Developing              65.4              226
273        Yemen  2012  Developing              64.7              236
274        Yemen  2011  Developing              64.6              234
275        Yemen  2010  Developing              64.4              233

     infant deaths  Hepatitis B  Measles    BMI   under-five deaths   Polio  \
0               62         65.0      1154   19.1                  83      6
1               64         62.0       492   18.6                  86     58
2               66         64.0       430   18.1                  89     62
3               69         67.0      2787   17.6                  93     67
4               71         68.0      3013   17.2                  97     68
..             ...          ...       ...    ...                 ...    ...
271             37         73.0       815    4.4                  47     67
272             36         73.0       400   39.6                  46     67
273             36         67.0      2177   38.7                  46     68
274             35         69.0      2676   37.9                  45     69
275             35         76.0       510   37.2                  45     77

     Diphtheria    HIV/AIDS          GDP    Population  \
0             65        0.1   584.259210  3.373649e+07
1             62        0.1   612.696514  3.275820e+05
2             64        0.1   631.744976  3.173169e+07
3             67        0.1   669.959000  3.696958e+06
4             68        0.1    63.537231  2.978599e+06
..           ...        ...          ...           ...
271           73        0.1  9319.472277  2.841118e+07
272           73        0.1  9319.472277  2.841118e+07
273           67        0.1  9319.472277  2.841118e+07
274           69        0.1  9319.472277  2.841118e+07
275           76        0.1  9319.472277  2.841118e+07

     Income composition of resources  Schooling
0                              0.479       10.1
1                              0.476       10.0
2                              0.470        9.9
3                              0.463        9.8
4                              0.454        9.5
..                               ...        ...
271                            0.500        9.0
272                            0.498        9.0
273                            0.494        9.0
274                            0.493        8.6
275                            0.488        8.5

[276 rows x 17 columns]

In [15]:
df.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Hepatitis B                        6
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
Income composition of resources    0
Schooling                          0
dtype: int64